cutvars:
  Pt:
    max:
    - 1.5
    - 2.0
    - 2.5
    - 3.0
    - 3.5
    - 4.0
    - 5.0
    - 6.0
    - 7.0
    - 8.0
    - 10.0
    - 12.0
    - 16.0
    - 24.0
    min:
    - 1.0
    - 1.5
    - 2.0
    - 2.5
    - 3.0
    - 3.5
    - 4.0
    - 5.0
    - 6.0
    - 7.0
    - 8.0
    - 10.0
    - 12.0
    - 16.0
    name: pt_cand
  score_FD:
    max:
    - 0.75
    - 0.75
    - 0.45
    - 0.5
    - 0.5
    - 0.4
    - 0.45
    - 0.45
    - 0.45
    - 0.45
    - 0.5
    - 0.6
    - 0.6
    - 0.7
    min:
    - 0.4
    - 0.5
    - 0.2
    - 0.3
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.3
    - 0.4
    - 0.4
    - 0.5
    name: score_FD
  score_bkg:
    max:
    - 0.02
    - 0.02
    - 0.03
    - 0.06
    - 0.07
    - 0.07
    - 0.07
    - 0.07
    - 0.07
    - 0.024
    - 0.006
    - 0.006
    - 0.1
    - 0.06
    min:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    name: score_bkg
fitrangemax:
- 1.95
- 1.95
- 1.95
- 1.95
- 1.95
- 1.95
- 1.95
- 1.95
- 1.95
- 1.95
- 1.97
- 2.04
- 2.17
- 2.17
fitrangemin:
- 1.75
- 1.75
- 1.75
- 1.75
- 1.75
- 1.75
- 1.75
- 1.75
- 1.7
- 1.7
- 1.66
- 1.66
- 1.66
- 1.66
icutset: 1
