# using sample with a given bdt cut set below
fit_options:
  BkgFuncVn: ["kLin"]
  BkgFunc: ["kLin"]
  Rebin: [1]
  inv_mass_bins: 
    steps: [0.01]
    MassMin: [1.76]
    MassMax: [2.02]
  use_inv_mass_bins: [false]

  Sigma:
    FixSigma: 0