cutvars:
  Pt:
    max:
    - 1.5
    - 2.0
    - 2.5
    - 3.0
    min:
    - 1.0
    - 1.5
    - 2.0
    - 2.5
    name: pt_cand
  score_FD:
    max:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    min:
    - 0.25000000000000006
    - 0.15000000000000002
    - 0.20000000000000004
    - 0.20000000000000004
    name: score_FD
  score_bkg:
    max:
    - 0.05
    - 0.05
    - 0.1
    - 0.1
    min:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    name: score_bkg
icutset: 2
