cutvars:
  Pt:
    max:
    - 7.0
    - 8.0
    - 10.0
    min:
    - 6.0
    - 7.0
    - 8.0
    name: pt_cand
  score_FD:
    max:
    - 0.65
    - 0.65
    - 0.75
    min:
    - 0.45
    - 0.45
    - 0.5
    name: score_FD
  score_bkg:
    max:
    - 0.1
    - 0.024
    - 0.002
    min:
    - 0.0
    - 0.0
    - 0.0
    name: score_bkg
icutset: 2
