cutvars:
  Pt:
    max:
    - 2.0
    min:
    - 1.5
    name: pt_cand
  score_FD:
    max:
    - 0.5
    min:
    - 0.0
    name: score_FD
  score_bkg:
    max:
    - 0.04
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.95
fitrangemin:
- 1.71
icutset: 0
