savecfg: true
savedistrs: true

output:
    leg_labels: # legend labels, keep the right number of classes
        Bkg: Background
        Prompt: Prompt D$^+$
        FD: Feed-down D$^+$
    out_labels: # output labels, keep the right number of classes
        Bkg: Bkg
        Prompt: Prompt
        FD: FD

pt_ranges: # ranges in pt to split the data in the ml training and testing
    min: [1, 3, 5, 8, 12] # list
    max: [3, 5, 8, 12, 24] # list

ml:
    raw_output: False # use raw_output (True) of probability (False) as output of the model
    saved_models: [    /home/mdicosta/flowDplus/MLtraining/50100/no_opt_chi2pca_fullsample_frac06/pt1_3/ModelHandler_pT_1_3.pickle,
                       /home/mdicosta/flowDplus/MLtraining/50100/no_opt_chi2pca_fullsample_frac06/pt3_5/ModelHandler_pT_3_5.pickle,
                       /home/mdicosta/flowDplus/MLtraining/50100/no_opt_chi2pca_fullsample_frac06/pt5_8/ModelHandler_pT_5_8.pickle,
                       /home/mdicosta/flowDplus/MLtraining/50100/no_opt_chi2pca_fullsample_frac06/pt8_12/ModelHandler_pT_8_12.pickle,
                       /home/mdicosta/flowDplus/MLtraining/50100/no_opt_chi2pca_fullsample_frac06/pt12_24/ModelHandler_pT_12_24.pickle
                   ] # list of saved ModelHandler (path+file), compatible with the pt bins

appl: 
    column_to_save_list: ['fM', 'fPt'] # list of variables saved in the dataframes with the applied models

standalone_appl:
    treename: null # null if using parquet
    inputs: [
             /data/shared/DplFlowML/MLtrees/MC/Train306228/HF_LHC24g2_2P3PDstar_50100_PromptDplus_frac0.4.parquet,
             /data/shared/DplFlowML/MLtrees/MC/Train306228/HF_LHC24g2_2P3PDstar_50100_NonPromptDplus_frac0.4.parquet,
             /data/shared/DplFlowML/MLtrees/Data/Train305807/HF_LHC23zzh_pass4_small_2P3PDstar_50100.parquet
            ] # list of parquet files for the model application
    output_names: [
                    Prompt,
                    NonPrompt,
                    Bkg,
                  ] # names for the outputs (one for each file)
    output_dir: /home/mdicosta/flowDplus/MLtraining/50100/apply_50100_noopt_chi2pca # output directory
