cutvars:
  Pt:
    max:
    - 3.0
    min:
    - 2.5
    name: pt_cand
  score_FD:
    max:
    - 0.3
    min:
    - 0.0
    name: score_FD
  score_bkg:
    max:
    - 0.06
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.92
fitrangemin:
- 1.79
icutset: 0
