BkgFunc:
- kPol2
BkgFuncVn:
- kPol3
BoundMean: 0
Bspecie: Ball
Dmeson: Dplus
DrawVnComps: false
FixMean:
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
FixSigma:
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
FixSigmaRatio: 0
FixSigmaToFirstPeak: 0
InclRefl: false
InclSecPeak:
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
IncludeTempls: false
MassMax:
- 2.16
MassMin:
- 1.7
MeanFile: ''
NSigma4SB:
- 4
- 4
- 4
- 4
- 4
- 4
- 4
- 4
- 4
- 4
- 4
- 3
- 3
- 1
Rebin:
- 4
ReflFile: ''
ReflFunc: ''
SgnFunc:
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
Sigma:
- 0.025
SigmaFile: ''
SigmaFileSecPeak: ''
SigmaMultFactor: 1.0
SigmaMultFactorSecPeak: 1.0
SigmaRatioFile: ''
SigmaSecPeak:
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
UseLikelihood: 1
anresdir: ''
axestokeep:
- Mass
- sp
- score_FD
- score_bkg
- Pt
centrality: k3040
combined: true
correlatedPath: /home/mdicosta/FlowDplus/FinalResults/3040final/cutvar_correlated
cut_variation:
  corr_bdt_cut:
    bkg_max:
    - 0.02
    sig:
      max:
      - 0.6
      min:
      - 0.04
      step:
      - 0.015
  uncorr_bdt_cut:
    bkg_max:
    - - 0.09
      - 0.06
      - 0.06
    sig:
    - max:
      - 0.5
      - 0.7
      - 1.0
      min:
      - 0.0
      - 0.5
      - 0.7
detA: FT0c
detB: FV0a
detC: TPCtot
eff_filename: /home/mdicosta/Datasets/eff/AnalysisResults_3050_334909.root
enableRef: false
flow_files:
- /home/mdicosta/Datasets/3050/MERGED_0.root
- /home/mdicosta/Datasets/3050/MERGED_1.root
- /home/mdicosta/Datasets/3050/MERGED_2.root
- /home/mdicosta/Datasets/3050/MERGED_3.root
- /home/mdicosta/Datasets/3050/MERGED_4.root
- /home/mdicosta/Datasets/3050/MERGED_5.root
- /home/mdicosta/Datasets/3050/MERGED_6.root
- /home/mdicosta/Datasets/3050/MERGED_7.root
- /home/mdicosta/Datasets/3050/MERGED_8.root
- /home/mdicosta/Datasets/3050/MERGED_9.root
- /home/mdicosta/Datasets/3050/MERGED_10.root
harmonic: 2
inv_mass_bins:
- - 1.7
  - 1.71
  - 1.72
  - 1.73
  - 1.74
  - 1.75
  - 1.76
  - 1.77
  - 1.78
  - 1.79
  - 1.8
  - 1.81
  - 1.82
  - 1.83
  - 1.84
  - 1.85
  - 1.86
  - 1.87
  - 1.8800000000000001
  - 1.8900000000000001
  - 1.9000000000000001
  - 1.9100000000000001
  - 1.9200000000000002
  - 1.9300000000000002
  - 1.9400000000000002
  - 1.9500000000000002
  - 1.9600000000000002
  - 1.9700000000000002
  - 1.9800000000000002
  - 1.9900000000000002
  - 2.0
  - 2.0100000000000002
  - 2.0200000000000005
  - 2.0300000000000002
  - 2.04
  - 2.0500000000000003
  - 2.0600000000000005
  - 2.0700000000000003
  - 2.08
  - 2.0900000000000003
  - 2.1000000000000005
  - 2.1100000000000003
  - 2.12
  - 2.1300000000000003
  - 2.1400000000000006
  - 2.1500000000000004
  - 2.16
minimisation:
  combined: true
  correlated: false
nworkers: 1
out_dir: /home/mdicosta/FlowDplus/FinalResults/3040final/fitsyst/latest/trails/pt_160_240
ptmaxs:
- 24.0
ptmins:
- 16.0
rebin: 1
res_file: /home/mdicosta/Datasets/Reso/resosp3040l_PASS4_full_PbPb_Reso.root
shapes:
  B:
    fonll: /home/mdicosta/FlowDplus/MLanalysis/PtWeights/fonll_pythia_beautyFFee_charmhadrons_5dot5tev_y0dot5.root
    tamu:
      enabled: true
      file:
        B: /home/mdicosta/alice/DmesonAnalysis/models/tamu/B_TAMU_RAA_5TeV_3050.txt
        Bs: ''
  D:
    fonll: /home/mdicosta/FlowDplus/MLanalysis/PtWeights/fonll_pythia_beautyFFee_charmhadrons_5dot5tev_y0dot5.root
    tamu:
      enabled: true
      file: /home/mdicosta/alice/DmesonAnalysis/models/tamu/PromptD0_TAMU_RAA_5TeV_3050.txt
skimDir: /home/mdicosta/Datasets/3050/skim3040keepbkg/pre/AnRes/
skim_out_dir: /home/mdicosta/FlowDplus/FinalResults/3040final/fitsyst/latest
smooth: 100
suffix: config_3040_combined_FixSigma-2_BkgFuncVn-1_BkgFunc-1_Rebin-1_inv_mass_bins-11_MassMin-11_MassMax-11
use_inv_mass_bins: false
vn_method: sp
