cutvars:
  Pt:
    max:
    - 8.0
    min:
    - 7.0
    name: pt_cand
  score_FD:
    max:
    - 0.85
    min:
    - 0.65
    name: score_FD
  score_bkg:
    max:
    - 0.004
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.92
fitrangemin:
- 1.7
icutset: 3
