cutvars:
  Pt:
    max:
    - 3.0
    min:
    - 2.5
    name: pt_cand
  score_FD:
    max:
    - 0.75
    min:
    - 0.5
    name: score_FD
  score_bkg:
    max:
    - 0.01
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.95
fitrangemin:
- 1.71
icutset: 2
