cutvars:
  Pt:
    max:
    - 1.5
    - 2.0
    - 2.5
    - 3.0
    - 3.5
    - 4.0
    - 5.0
    - 6.0
    - 7.0
    - 8.0
    - 10.0
    - 12.0
    - 16.0
    - 24.0
    min:
    - 1.0
    - 1.5
    - 2.0
    - 2.5
    - 3.0
    - 3.5
    - 4.0
    - 5.0
    - 6.0
    - 7.0
    - 8.0
    - 10.0
    - 12.0
    - 16.0
    name: pt_cand
  score_FD:
    max:
    - 0.85
    - 0.75
    - 0.75
    - 0.75
    - 0.75
    - 0.75
    - 0.75
    - 0.75
    - 0.75
    - 0.75
    - 0.75
    - 0.75
    - 0.75
    - 0.75
    min:
    - 0.6
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    name: score_FD
  score_bkg:
    max:
    - 0.01
    - 0.01
    - 0.012
    - 0.012
    - 0.02
    - 0.02
    - 0.05
    - 0.05
    - 0.07
    - 0.07
    - 0.006
    - 0.006
    - 0.12
    - 0.12
    min:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    name: score_bkg
icutset: 2
