cutvars:
  Pt:
    max:
    - 1.5
    - 2.0
    - 2.5
    - 3.0
    - 3.5
    - 4.0
    - 5.0
    - 6.0
    - 7.0
    - 8.0
    - 10.0
    - 12.0
    - 16.0
    - 24.0
    min:
    - 1.0
    - 1.5
    - 2.0
    - 2.5
    - 3.0
    - 3.5
    - 4.0
    - 5.0
    - 6.0
    - 7.0
    - 8.0
    - 10.0
    - 12.0
    - 16.0
    name: pt_cand
  score_FD:
    max:
    - 0.95
    - 0.95
    - 0.75
    - 0.75
    - 0.7
    - 0.7
    - 0.65
    - 0.65
    - 0.65
    - 0.65
    - 0.75
    - 0.75
    - 0.8
    - 1.0
    min:
    - 0.75
    - 0.75
    - 0.45
    - 0.5
    - 0.5
    - 0.4
    - 0.45
    - 0.45
    - 0.45
    - 0.45
    - 0.5
    - 0.6
    - 0.6
    - 0.7
    name: score_FD
  score_bkg:
    max:
    - 0.008
    - 0.02
    - 0.01
    - 0.01
    - 0.03
    - 0.03
    - 0.006
    - 0.04
    - 0.02
    - 0.024
    - 0.002
    - 0.002
    - 0.002
    - 0.06
    min:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    name: score_bkg
fitrangemax:
- 2.04
- 2.04
- 2.04
- 2.04
- 2.04
- 2.04
- 2.04
- 2.04
- 2.04
- 2.04
- 2.04
- 2.04
- 2.16
- 2.16
fitrangemin:
- 1.76
- 1.76
- 1.76
- 1.76
- 1.76
- 1.76
- 1.76
- 1.76
- 1.76
- 1.76
- 1.76
- 1.76
- 1.76
- 1.76
icutset: 2
