cutvars:
  Pt:
    max:
    - 4.0
    min:
    - 3.5
    name: pt_cand
  score_FD:
    max:
    - 0.25
    min:
    - 0.0
    name: score_FD
  score_bkg:
    max:
    - 0.1
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.95
fitrangemin:
- 1.75
icutset: 0
