cutvars:
  Pt:
    max:
    - 10.0
    min:
    - 8.0
    name: pt_cand
  score_FD:
    max:
    - 0.75
    min:
    - 0.5
    name: score_FD
  score_bkg:
    max:
    - 0.002
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.97
fitrangemin:
- 1.71
icutset: 2
