cutvars:
  Pt:
    max:
    - 7.0
    min:
    - 6.0
    name: pt_cand
  score_FD:
    max:
    - 0.45
    min:
    - 0.25
    name: score_FD
  score_bkg:
    max:
    - 0.07
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.98
fitrangemin:
- 1.71
icutset: 1
