cutvars:
  Pt:
    max:
    - 5.0
    min:
    - 4.0
    name: pt_cand
  score_FD:
    max:
    - 0.85
    min:
    - 0.65
    name: score_FD
  score_bkg:
    max:
    - 0.006
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.92
fitrangemin:
- 1.79
icutset: 3
