cutvars:
  Pt:
    max:
    - 6.0
    min:
    - 5.0
    name: pt_cand
  score_FD:
    max:
    - 0.85
    min:
    - 0.65
    name: score_FD
  score_bkg:
    max:
    - 0.01
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.98
fitrangemin:
- 1.71
icutset: 3
