cutvars:
  Pt:
    max:
    - 16.0
    min:
    - 12.0
    name: pt_cand
  score_FD:
    max:
    - 0.4
    min:
    - 0.0
    name: score_FD
  score_bkg:
    max:
    - 0.2
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 2.08
fitrangemin:
- 1.66
icutset: 0
