# global info (do not change)      
axes: {mass: 0,
       pt: 1,
       cent: 2,
       sp: 3,
       deltaphi: 15,
       phi: 16,
       bdt_bkg: 4,
       bdt_sig: 5}

# axes: {mass: 0,
#        pt: 1,
#        cent: 2,
#        sp: 3,
#        occupancy: 4,
#        evselbits: 5}

harmonic: 2 # 2: v2, 3: v3, etc.

# pt bins
ptmins: [
           1.0,
           1.5,
           2.0,
           2.5,
           3.0,
           3.5,
           4.0,
           5.0,
           6.0,
           7.0,
           8.0,
           10.0,
           12.0,
           16.0
       ]
ptmaxs: [
           1.5,
           2.0,
           2.5,
           3.0,
           3.5,
           4.0,
           5.0,
           6.0,
           7.0,
           8.0,
           10.0,
           12.0,
           16.0,
           24.0
       ]

# inv_mass_bins (one for each pt bin)
inv_mass_bins: [ 
                 [1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                 [1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                 [1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                 [1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                 [1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                 [1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                 [1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                 [1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                 [1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                 [1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                 [1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],
                 [1.71,1.73,1.75,1.77,1.79,1.81,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.91,1.93,1.95,1.97,1.99,2.01,2.03,2.05],
                 [1.71,1.73,1.75,1.76,1.77,1.79,1.81,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.91,1.93,1.95,1.97,1.99,2.01,2.03,2.05],
                 [1.70,1.73,1.76,1.79,1.82,1.84,1.86,1.88,1.90,1.93,1.96,1.99,2.02,2.05],
]
use_inv_mass_bins: false

skimDir: /Users/mcosti/Analysis/Datasets/6080/skim6080/pre/AnRes/
axestokeep: ['Mass', 'sp', 'score_FD', 'Pt', 'cent']

# bdt cut
apply_btd_cuts: false # apply bdt cuts

# ep/sp subevents
detA: 'FT0c'
detB: 'FV0a'
detC: 'TPCtot'

centrality: 'k6080'

# fit options
Dmeson: 'Dplus'
br: 0.0938 # branching ratio
FixSigma: [
           1,
           1,
           1,
           1,
           1,
           1,
           1,
           1,
           1,
           1,
           1,
           1,
           1,
           1,
          ] 
SigmaFile: ''
SigmaMultFactor: 1.
FixMean: [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
         ]
NSigma4SB: [
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            3,
            3,
            3,
            3,
            1
           ]
MeanFile: ''
MassMin: [
          1.77, 
          1.75, 
          1.75, 
          1.75, 
          1.75, 
          1.75, 
          1.75, 
          1.75, 
          1.75,
          1.72, 
          1.70, 
          1.70, 
          1.70, 
          1.70, 
       ]
MassMax: [
          1.95,
          1.97, 
          1.97, 
          1.97, 
          1.97, 
          1.97, 
          1.98, 
          1.98, 
          1.95, 
          2.00, 
          2.05, 
          2.05, 
          2.05, 
          2.04, 
       ]
Rebin: [
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        4,
        4,
        4,
       ]
InclSecPeak: [
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
             ]
Sigma: [
        0.012,
        0.012,
        0.012,
        0.012,
        0.012,
        0.012,
        0.020,
        0.020,
        0.020,
        0.020,
        0.025,
        0.025,
        0.025,
        0.025,
       ]
SigmaSecPeak: [
               0.008,
               0.008,
               0.008,
               0.008,
               0.008,
               0.008,
               0.008,
               0.008,
               0.008,
               0.008,
               0.008,
               0.008,
               0.008,
               0.008,
              ]
SigmaFileSecPeak: ''
SigmaMultFactorSecPeak: 1.
FixSigmaToFirstPeak: 0
UseLikelihood: 1
BkgFunc: [ 
           'kLin',
           'kLin', 
           'kLin', 
           'kLin', 
           'kLin', 
           'kLin', 
           'kLin', 
           'kLin', 
           'kLin', 
           'kLin', 
           'kLin',
           'kLin', 
           'kLin', 
           'kLin', 
         ]
SgnFunc: [
          'kGaus',
          'kGaus', 
          'kGaus', 
          'kGaus', 
          'kGaus', 
          'kGaus', 
          'kGaus', 
          'kGaus', 
          'kGaus', 
          'kGaus', 
          'kGaus',
          'kGaus',
          'kGaus',
          'kGaus',
       ]
BkgFuncVn: [
            'kLin', 
            'kLin',   
            'kLin',   
            'kLin',   
            'kLin',   
            'kLin', 
            'kLin', 
            'kLin', 
            'kLin', 
            'kLin', 
            'kLin', 
            'kLin',
            'kLin',
            'kLin',
           ]

FixSigmaRatio: 0 # used only if SgnFunc = kGausSigmaRatioPar
SigmaRatioFile: ""
BoundMean: 0 # 0: Do not set limits on mean range, 1: the mean is set to be between MassMin[i] and MassMax[i]
InclRefl: false
enableRef: false
ReflFile: ''
ReflFunc: ''
DrawVnComps: false
IncludeKDETempls: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
