cutvars:
  Pt:
    max:
    - 7.0
    min:
    - 6.0
    name: pt_cand
  score_FD:
    max:
    - 0.25
    min:
    - 0.0
    name: score_FD
  score_bkg:
    max:
    - 0.1
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.95
fitrangemin:
- 1.79
icutset: 0
