cutvars:
  Pt:
    max:
    - 12.0
    min:
    - 10.0
    name: pt_cand
  score_FD:
    max:
    - 0.4
    min:
    - 0.0
    name: score_FD
  score_bkg:
    max:
    - 0.006
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 2.04
fitrangemin:
- 1.69
icutset: 0
