cutvars:
  Pt:
    max:
    - 8.0
    min:
    - 7.0
    name: pt_cand
  score_FD:
    max:
    - 0.45
    min:
    - 0.25
    name: score_FD
  score_bkg:
    max:
    - 0.024
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.95
fitrangemin:
- 1.71
icutset: 1
