BkgFunc:
- kLin
BkgFuncVn:
- kPol2
BoundMean: 0
Bspecie: Ball
Dmeson: Dplus
DrawVnComps: false
FixMean:
- 1
FixSigma:
- 0
FixSigmaRatio: 0
FixSigmaToFirstPeak: 0
InclRefl: false
InclSecPeak:
- 0
IncludeTempls: false
MassMax:
- 2.17
MassMin:
- 1.75
MaxChi2: 20
MaxSignificance: 500
MeanFile: ''
MinSignificance: 5
NSigma4SB:
- 1
Rebin:
- 3
ReflFile: ''
ReflFunc: ''
SgnFunc:
- kGaus
Sigma:
- 0.025
SigmaFile: ''
SigmaFileSecPeak: ''
SigmaMultFactor: 1.0
SigmaMultFactorSecPeak: 1.0
SigmaRatioFile: ''
SigmaSecPeak:
- 0.008
UseLikelihood: 1
anresdir: ''
axestokeep:
- Mass
- sp
- score_FD
- score_bkg
- Pt
centrality: k4050
combined: true
correlatedPath: /home/mdicosta/FlowDplus/FinalResults/4050final/cutvar_correlated
cut_variation:
  corr_bdt_cut:
    bkg_max:
    - 0.02
    sig:
      max:
      - 0.6
      min:
      - 0.04
      step:
      - 0.015
  uncorr_bdt_cut:
    bkg_max:
    - - 0.06
      - 0.06
      - 0.06
    sig:
    - max:
      - 0.5
      - 0.7
      - 1.0
      min:
      - 0.0
      - 0.5
      - 0.7
detA: FT0c
detB: FV0a
detC: TPCtot
eff_filename: /home/mdicosta/Datasets/eff/AnalysisResults_3050_334909.root
enableRef: false
harmonic: 2
inv_mass_bins:
- - 1.65
  - 1.69
  - 1.73
  - 1.77
  - 1.81
  - 1.83
  - 1.85
  - 1.87
  - 1.89
  - 1.91
  - 1.93
  - 1.97
  - 2.01
  - 2.05
  - 2.09
  - 2.13
  - 2.17
minimisation:
  correlated: false
nworkers: 1
out_dir: /home/mdicosta/FlowDplus/FinalResults/4050final/multitrial_ptdiff/pt_160_240/trails/
ptmaxs:
- 24.0
ptmins:
- 16.0
rebin: 1
res_file: /home/mdicosta/Datasets/Reso/resosp4050l_PASS4_full_PbPb_Reso.root
shapes:
  B:
    fonll: /home/mdicosta/FlowDplus/MLanalysis/PtWeights/fonll_pythia_beautyFFee_charmhadrons_5dot5tev_y0dot5.root
    tamu:
      enabled: true
      file:
        B: /home/mdicosta/alice/DmesonAnalysis/models/tamu/B_TAMU_RAA_5TeV_3050.txt
        Bs: ''
  D:
    fonll: /home/mdicosta/FlowDplus/MLanalysis/PtWeights/fonll_pythia_beautyFFee_charmhadrons_5dot5tev_y0dot5.root
    tamu:
      enabled: true
      file: /home/mdicosta/alice/DmesonAnalysis/models/tamu/PromptD0_TAMU_RAA_5TeV_3050.txt
skimDir: /home/mdicosta/Datasets/3050/skim4050keepbkg/pre/AnRes/
skim_out_dir: /home/mdicosta/Datasets/3050/skim4050keepbkg/
smooth: 100
suffix: '321'
use_inv_mass_bins: false
vn_method: sp
