cutvars:
  Pt:
    max:
    - 6.0
    min:
    - 5.0
    name: pt_cand
  score_FD:
    max:
    - 1.0
    min:
    - 0.85
    name: score_FD
  score_bkg:
    max:
    - 0.004
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.95
fitrangemin:
- 1.71
icutset: 4
