cutvars:
  Pt:
    max:
    - 12.0
    min:
    - 10.0
    name: pt_cand
  score_FD:
    max:
    - 0.75
    min:
    - 0.6
    name: score_FD
  score_bkg:
    max:
    - 0.002
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 2.01
fitrangemin:
- 1.72
icutset: 2
