cutvars:
  Pt:
    max:
    - 1.5
    min:
    - 1.0
    name: pt_cand
  score_FD:
    max:
    - 0.4
    min:
    - 0.0
    name: score_FD
  score_bkg:
    max:
    - 0.03
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.95
fitrangemin:
- 1.75
icutset: 0
