cutvars:
  Pt:
    max:
    - 16.0
    min:
    - 12.0
    name: pt_cand
  score_FD:
    max:
    - 0.6
    min:
    - 0.4
    name: score_FD
  score_bkg:
    max:
    - 0.1
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 2.13
fitrangemin:
- 1.7
icutset: 1
