cutvars:
  Pt:
    max:
    - 5.0
    min:
    - 4.0
    name: pt_cand
  score_FD:
    max:
    - 1.0
    min:
    - 0.0
    name: score_FD
  score_bkg:
    max:
    - 0.015
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.95
fitrangemin:
- 1.75
icutset: 0
