centrality: 'k3040' 
anresdir: '' 
res_file: '/home/mdicosta/Datasets/Reso/resosp3040l_PASS4_full_PbPb_Reso.root'
out_dir: '/home/mdicosta/FlowDplus/FinalResults/3040final'
skim_out_dir: /home/mdicosta/Datasets/3050/skim3040keepbkg/
suffix: 'combined_15_20'
vn_method: 'sp'
Dmeson: 'Dplus'
nworkers: 40

flow_files: [
  /home/mdicosta/Datasets/3050/MERGED_0.root,
  /home/mdicosta/Datasets/3050/MERGED_1.root,
  /home/mdicosta/Datasets/3050/MERGED_2.root,
  /home/mdicosta/Datasets/3050/MERGED_3.root,
  /home/mdicosta/Datasets/3050/MERGED_4.root,
  /home/mdicosta/Datasets/3050/MERGED_5.root,
  /home/mdicosta/Datasets/3050/MERGED_6.root,
  /home/mdicosta/Datasets/3050/MERGED_7.root,
  /home/mdicosta/Datasets/3050/MERGED_8.root,
  /home/mdicosta/Datasets/3050/MERGED_9.root,
  /home/mdicosta/Datasets/3050/MERGED_10.root,
]


minimisation:
    correlated: false # true --> fully correlated, false --> fully uncorrelated

combined: true
correlatedPath: '/home/mdicosta/FlowDplus/FinalResults/3040final/cutvar_correlated'

# ep/sp subevents
detA: 'FT0c'
detB: 'FV0a'
detC: 'TPCtot'

eff_filename: /home/mdicosta/Datasets/eff/AnalysisResults_3050_334909.root

skimDir: /home/mdicosta/Datasets/3050/skim3040keepbkg/pre/AnRes/
axestokeep: ['Mass', 'sp', 'score_FD', 'score_bkg', 'Pt']
harmonic: 2 # 2: v2, 3: v3, etc.



## used for computing pT weights
Bspecie: Ball # only surport for Ball and BsBmix, empty means no B pt weights
rebin: 1
smooth: 100
shapes:
    D:
        # fonll is mandatory
        fonll: /home/mdicosta/FlowDplus/MLanalysis/PtWeights/fonll_pythia_beautyFFee_charmhadrons_5dot5tev_y0dot5.root
        tamu:
              enabled: true
              file: /home/mdicosta/alice/DmesonAnalysis/models/tamu/PromptD0_TAMU_RAA_5TeV_3050.txt
        #TODO: data shape for Ds?
    B:
        # fonll is mandatory
        fonll: /home/mdicosta/FlowDplus/MLanalysis/PtWeights/fonll_pythia_beautyFFee_charmhadrons_5dot5tev_y0dot5.root
        tamu:
            enabled: true
            file: 
                B: /home/mdicosta/alice/DmesonAnalysis/models/tamu/B_TAMU_RAA_5TeV_3050.txt
                Bs: ''

# pt bins
ptmins: [
           1.5,
       ]
ptmaxs: [
           2.0,
           ]

# inv_mass_bins (one for each pt bin)
inv_mass_bins: [
                 [1.70,1.72,1.73,1.74,1.75,1.76,1.77,1.78,1.79,1.80,1.81,1.82,1.83,1.84,1.85,1.86,1.87,1.88,1.89,1.90,1.91,1.92,1.93,1.94,1.95,1.96,1.97,1.98,1.99,2.00,2.01,2.02,2.03,2.04,2.05],

                #  [1.70,1.72,1.74,1.76,1.78,1.80,1.82,1.84,1.86,1.88,1.90,1.92,1.94,1.96,1.98,2.00,2.02,2.04,2.05],
                ]
use_inv_mass_bins: false

# cut variation
cut_variation:
       corr_bdt_cut:
              bkg_max: [0.004]
              sig: # the max value is not contained in the range
                min: [0.06]
                max: [1.0]
                step: [0.025]
       uncorr_bdt_cut:
            bkg_max: # max probability for bkg, one for each pt bin
                - [0.04, 0.02, 0.02, 0.002] # pt 2
            sig:
                - min: [0.00, 0.50, 0.70, 0.90] # min pt 2
                  max: [0.50, 0.70, 0.90, 1.00] # max pt 2
            
# fit options
FixSigma: [
           0,
           ] 
SigmaFile: ''
SigmaMultFactor: 1.
FixMean: [
          1,
          ]
NSigma4SB: [
            4,
          ]
MeanFile: ''
MassMin: [
          1.75,
          ]
MassMax: [
          1.95,
          ]
Rebin: [
        2,
       ]
InclSecPeak: [
              0,
             ]
Sigma: [
        0.012,
        ]
SigmaSecPeak: [
               0.008,
              ]
SigmaFileSecPeak: ''
SigmaMultFactorSecPeak: 1.
FixSigmaToFirstPeak: 0
UseLikelihood: 1
BkgFunc: [ 
           'kLin',
         ]
SgnFunc: [
          'kGaus',
       ]
BkgFuncVn: [
            'kLin',
           ]

FixSigmaRatio: 0 # used only if SgnFunc = kGausSigmaRatioPar
SigmaRatioFile: ""
BoundMean: 0 # 0: Do not set limits on mean range, 1: the mean is set to be between MassMin[i] and MassMax[i]
InclRefl: false
enableRef: false
ReflFile: ''
ReflFunc: ''

DrawVnComps: false
IncludeTempls: False

smooth: 100






# BkgFunc:
# - kLin
# - kLin
# - kLin
# - kLin
# - kLin
# - kLin
# - kLin
# - kLin
# - kLin
# - kLin
# - kLin
# - kLin
# - kLin
# - kLin
# BkgFuncVn:
# - kLin
# - kLin
# - kLin
# - kLin
# - kLin
# - kLin
# - kLin
# - kLin
# - kLin
# - kLin
# - kLin
# - kLin
# - kLin
# - kLin
# BoundMean: 0
# Bspecie: Ball
# Dmeson: Dplus
# DrawVnComps: false
# FixMean:
# - 1
# - 1
# - 1
# - 1
# - 1
# - 1
# - 1
# - 1
# - 1
# - 1
# - 1
# - 1
# - 1
# - 1
# FixSigma:
# - 0
# - 0
# - 0
# - 0
# - 0
# - 0
# - 0
# - 0
# - 0
# - 0
# - 0
# - 0
# - 0
# - 0
# FixSigmaRatio: 0
# FixSigmaToFirstPeak: 0
# InclRefl: false
# InclSecPeak:
# - 0
# - 0
# - 0
# - 0
# - 0
# - 0
# - 0
# - 0
# - 0
# - 0
# - 0
# - 0
# - 0
# - 0
# IncludeTempls: false
# MassMax:
# - 2.04
# - 2.04
# - 2.04
# - 2.04
# - 2.04
# - 2.04
# - 2.04
# - 2.04
# - 2.04
# - 2.04
# - 2.04
# - 2.04
# - 2.16
# - 2.16
# MassMin:
# - 1.7
# - 1.7
# - 1.7
# - 1.7
# - 1.7
# - 1.7
# - 1.7
# - 1.7
# - 1.7
# - 1.7
# - 1.7
# - 1.7
# - 1.7
# - 1.7
# MeanFile: ''
# NSigma4SB:
# - 4
# - 4
# - 4
# - 4
# - 4
# - 4
# - 4
# - 4
# - 4
# - 4
# - 4
# - 3
# - 3
# - 1
# Rebin:
# - 3
# - 3
# - 2
# - 2
# - 2
# - 2
# - 2
# - 2
# - 2
# - 2
# - 2
# - 3
# - 5
# - 5
# ReflFile: ''
# ReflFunc: ''
# SgnFunc:
# - kGaus
# - kGaus
# - kGaus
# - kGaus
# - kGaus
# - kGaus
# - kGaus
# - kGaus
# - kGaus
# - kGaus
# - kGaus
# - kGaus
# - kGaus
# - kGaus
# Sigma:
# - 0.012
# - 0.012
# - 0.012
# - 0.012
# - 0.012
# - 0.012
# - 0.02
# - 0.02
# - 0.02
# - 0.02
# - 0.02
# - 0.02
# - 0.025
# - 0.025
# SigmaFile: ''
# SigmaFileSecPeak: ''
# SigmaMultFactor: 1.0
# SigmaMultFactorSecPeak: 1.0
# SigmaRatioFile: ''
# SigmaSecPeak:
# - 0.008
# - 0.008
# - 0.008
# - 0.008
# - 0.008
# - 0.008
# - 0.008
# - 0.008
# - 0.008
# - 0.008
# - 0.008
# - 0.008
# - 0.008
# - 0.008
# UseLikelihood: 1
# anresdir: ''
# axestokeep:
# - Mass
# - sp
# - score_FD
# - score_bkg
# - Pt
# centrality: k3040
# combined: true
# correlatedPath: /home/mdicosta/FlowDplus/FinalResults/3040final/cutvar_correlated
# cut_variation:
#   corr_bdt_cut:
#     bkg_max:
#     - 0.004
#     - 0.004
#     - 0.015
#     - 0.015
#     - 0.02
#     - 0.02
#     - 0.015
#     - 0.015
#     - 0.01
#     - 0.01
#     - 0.006
#     - 0.006
#     - 0.02
#     - 0.02
#     sig:
#       max:
#       - 1.0
#       - 1.0
#       - 1.0
#       - 1.0
#       - 1.0
#       - 1.0
#       - 1.0
#       - 1.0
#       - 1.0
#       - 1.0
#       - 1.0
#       - 1.0
#       - 0.6
#       - 0.6
#       min:
#       - 0.06
#       - 0.06
#       - 0.06
#       - 0.06
#       - 0.06
#       - 0.06
#       - 0.06
#       - 0.06
#       - 0.06
#       - 0.06
#       - 0.06
#       - 0.06
#       - 0.04
#       - 0.04
#       step:
#       - 0.025
#       - 0.025
#       - 0.025
#       - 0.025
#       - 0.025
#       - 0.025
#       - 0.025
#       - 0.025
#       - 0.025
#       - 0.025
#       - 0.025
#       - 0.025
#       - 0.015
#       - 0.015
#   uncorr_bdt_cut:
#     bkg_max:
#     - - 0.01
#       - 0.02
#       - 0.008
#       - 0.004
#     - - 0.04
#       - 0.02
#       - 0.02
#       - 0.002
#     - - 0.03
#       - 0.03
#       - 0.01
#       - 0.006
#       - 0.002
#     - - 0.06
#       - 0.06
#       - 0.01
#       - 0.006
#       - 0.004
#     - - 0.06
#       - 0.06
#       - 0.03
#       - 0.01
#       - 0.004
#     - - 0.1
#       - 0.07
#       - 0.03
#       - 0.004
#       - 0.006
#     - - 0.03
#       - 0.01
#       - 0.006
#       - 0.006
#       - 0.004
#     - - 0.1
#       - 0.1
#       - 0.04
#       - 0.01
#       - 0.004
#     - - 0.02
#       - 0.02
#       - 0.02
#       - 0.006
#       - 0.002
#     - - 0.024
#       - 0.024
#       - 0.024
#       - 0.004
#       - 0.002
#     - - 0.006
#       - 0.006
#       - 0.002
#       - 0.002
#     - - 0.006
#       - 0.006
#       - 0.002
#       - 0.002
#     - - 0.15
#       - 0.15
#       - 0.15
#       - 0.05
#     - - 0.06
#       - 0.06
#       - 0.06
#     sig:
#     - max:
#       - 0.4
#       - 0.65
#       - 0.85
#       - 1.0
#       min:
#       - 0.0
#       - 0.4
#       - 0.65
#       - 0.85
#     - max:
#       - 0.2
#       - 0.4
#       - 0.65
#       - 1.0
#       min:
#       - 0.0
#       - 0.2
#       - 0.4
#       - 0.65
#     - max:
#       - 0.2
#       - 0.45
#       - 0.75
#       - 0.9
#       - 1.0
#       min:
#       - 0.0
#       - 0.2
#       - 0.45
#       - 0.75
#       - 0.9
#     - max:
#       - 0.3
#       - 0.5
#       - 0.75
#       - 0.9
#       - 1.0
#       min:
#       - 0.0
#       - 0.3
#       - 0.5
#       - 0.75
#       - 0.9
#     - max:
#       - 0.3
#       - 0.5
#       - 0.7
#       - 0.85
#       - 1.0
#       min:
#       - 0.0
#       - 0.3
#       - 0.5
#       - 0.7
#       - 0.85
#     - max:
#       - 0.25
#       - 0.4
#       - 0.7
#       - 0.9
#       - 1.0
#       min:
#       - 0.0
#       - 0.25
#       - 0.4
#       - 0.7
#       - 0.9
#     - max:
#       - 0.25
#       - 0.45
#       - 0.65
#       - 0.85
#       - 1.0
#       min:
#       - 0.0
#       - 0.25
#       - 0.45
#       - 0.65
#       - 0.85
#     - max:
#       - 0.25
#       - 0.45
#       - 0.65
#       - 0.85
#       - 1.0
#       min:
#       - 0.0
#       - 0.25
#       - 0.45
#       - 0.65
#       - 0.85
#     - max:
#       - 0.25
#       - 0.45
#       - 0.65
#       - 0.85
#       - 1.0
#       min:
#       - 0.0
#       - 0.25
#       - 0.45
#       - 0.65
#       - 0.85
#     - max:
#       - 0.25
#       - 0.45
#       - 0.65
#       - 0.85
#       - 1.0
#       min:
#       - 0.0
#       - 0.25
#       - 0.45
#       - 0.65
#       - 0.85
#     - max:
#       - 0.3
#       - 0.5
#       - 0.75
#       - 1.0
#       min:
#       - 0.0
#       - 0.3
#       - 0.5
#       - 0.75
#     - max:
#       - 0.4
#       - 0.6
#       - 0.75
#       - 1.0
#       min:
#       - 0.0
#       - 0.4
#       - 0.6
#       - 0.75
#     - max:
#       - 0.4
#       - 0.6
#       - 0.75
#       - 1.0
#       min:
#       - 0.0
#       - 0.4
#       - 0.6
#       - 0.75
#     - max:
#       - 0.5
#       - 0.7
#       - 1.0
#       min:
#       - 0.0
#       - 0.5
#       - 0.7
# detA: FT0c
# detB: FV0a
# detC: TPCtot
# eff_filename: /home/mdicosta/Datasets/eff/AnalysisResults_3050_334909.root
# enableRef: false
# flow_files:
# - /home/mdicosta/Datasets/3050/MERGED_0.root
# - /home/mdicosta/Datasets/3050/MERGED_1.root
# - /home/mdicosta/Datasets/3050/MERGED_2.root
# - /home/mdicosta/Datasets/3050/MERGED_3.root
# - /home/mdicosta/Datasets/3050/MERGED_4.root
# - /home/mdicosta/Datasets/3050/MERGED_5.root
# - /home/mdicosta/Datasets/3050/MERGED_6.root
# - /home/mdicosta/Datasets/3050/MERGED_7.root
# - /home/mdicosta/Datasets/3050/MERGED_8.root
# - /home/mdicosta/Datasets/3050/MERGED_9.root
# - /home/mdicosta/Datasets/3050/MERGED_10.root
# harmonic: 2
# inv_mass_bins:
# - - 1.7
#   - 1.72
#   - 1.74
#   - 1.76
#   - 1.78
#   - 1.8
#   - 1.82
#   - 1.84
#   - 1.86
#   - 1.8800000000000001
#   - 1.9000000000000001
#   - 1.9200000000000002
#   - 1.9400000000000002
#   - 1.9600000000000002
#   - 1.9800000000000002
#   - 2.0
#   - 2.0200000000000005
#   - 2.04
# - - 1.7
#   - 1.72
#   - 1.74
#   - 1.76
#   - 1.78
#   - 1.8
#   - 1.82
#   - 1.84
#   - 1.86
#   - 1.8800000000000001
#   - 1.9000000000000001
#   - 1.9200000000000002
#   - 1.9400000000000002
#   - 1.9600000000000002
#   - 1.9800000000000002
#   - 2.0
#   - 2.0200000000000005
#   - 2.04
# - - 1.7
#   - 1.72
#   - 1.74
#   - 1.76
#   - 1.78
#   - 1.8
#   - 1.82
#   - 1.84
#   - 1.86
#   - 1.8800000000000001
#   - 1.9000000000000001
#   - 1.9200000000000002
#   - 1.9400000000000002
#   - 1.9600000000000002
#   - 1.9800000000000002
#   - 2.0
#   - 2.0200000000000005
#   - 2.04
# - - 1.7
#   - 1.72
#   - 1.74
#   - 1.76
#   - 1.78
#   - 1.8
#   - 1.82
#   - 1.84
#   - 1.86
#   - 1.8800000000000001
#   - 1.9000000000000001
#   - 1.9200000000000002
#   - 1.9400000000000002
#   - 1.9600000000000002
#   - 1.9800000000000002
#   - 2.0
#   - 2.0200000000000005
#   - 2.04
# - - 1.7
#   - 1.72
#   - 1.74
#   - 1.76
#   - 1.78
#   - 1.8
#   - 1.82
#   - 1.84
#   - 1.86
#   - 1.8800000000000001
#   - 1.9000000000000001
#   - 1.9200000000000002
#   - 1.9400000000000002
#   - 1.9600000000000002
#   - 1.9800000000000002
#   - 2.0
#   - 2.0200000000000005
#   - 2.04
# - - 1.7
#   - 1.72
#   - 1.74
#   - 1.76
#   - 1.78
#   - 1.8
#   - 1.82
#   - 1.84
#   - 1.86
#   - 1.8800000000000001
#   - 1.9000000000000001
#   - 1.9200000000000002
#   - 1.9400000000000002
#   - 1.9600000000000002
#   - 1.9800000000000002
#   - 2.0
#   - 2.0200000000000005
#   - 2.04
# - - 1.7
#   - 1.72
#   - 1.74
#   - 1.76
#   - 1.78
#   - 1.8
#   - 1.82
#   - 1.84
#   - 1.86
#   - 1.8800000000000001
#   - 1.9000000000000001
#   - 1.9200000000000002
#   - 1.9400000000000002
#   - 1.9600000000000002
#   - 1.9800000000000002
#   - 2.0
#   - 2.0200000000000005
#   - 2.04
# - - 1.7
#   - 1.72
#   - 1.74
#   - 1.76
#   - 1.78
#   - 1.8
#   - 1.82
#   - 1.84
#   - 1.86
#   - 1.8800000000000001
#   - 1.9000000000000001
#   - 1.9200000000000002
#   - 1.9400000000000002
#   - 1.9600000000000002
#   - 1.9800000000000002
#   - 2.0
#   - 2.0200000000000005
#   - 2.04
# - - 1.7
#   - 1.72
#   - 1.74
#   - 1.76
#   - 1.78
#   - 1.8
#   - 1.82
#   - 1.84
#   - 1.86
#   - 1.8800000000000001
#   - 1.9000000000000001
#   - 1.9200000000000002
#   - 1.9400000000000002
#   - 1.9600000000000002
#   - 1.9800000000000002
#   - 2.0
#   - 2.0200000000000005
#   - 2.04
# - - 1.7
#   - 1.72
#   - 1.74
#   - 1.76
#   - 1.78
#   - 1.8
#   - 1.82
#   - 1.84
#   - 1.86
#   - 1.8800000000000001
#   - 1.9000000000000001
#   - 1.9200000000000002
#   - 1.9400000000000002
#   - 1.9600000000000002
#   - 1.9800000000000002
#   - 2.0
#   - 2.0200000000000005
#   - 2.04
# - - 1.7
#   - 1.72
#   - 1.74
#   - 1.76
#   - 1.78
#   - 1.8
#   - 1.82
#   - 1.84
#   - 1.86
#   - 1.8800000000000001
#   - 1.9000000000000001
#   - 1.9200000000000002
#   - 1.9400000000000002
#   - 1.9600000000000002
#   - 1.9800000000000002
#   - 2.0
#   - 2.0200000000000005
#   - 2.04
# - - 1.7
#   - 1.72
#   - 1.74
#   - 1.76
#   - 1.78
#   - 1.8
#   - 1.82
#   - 1.84
#   - 1.86
#   - 1.8800000000000001
#   - 1.9000000000000001
#   - 1.9200000000000002
#   - 1.9400000000000002
#   - 1.9600000000000002
#   - 1.9800000000000002
#   - 2.0
#   - 2.0200000000000005
#   - 2.04
# - - 1.7
#   - 1.72
#   - 1.74
#   - 1.76
#   - 1.78
#   - 1.8
#   - 1.82
#   - 1.84
#   - 1.86
#   - 1.8800000000000001
#   - 1.9000000000000001
#   - 1.9200000000000002
#   - 1.9400000000000002
#   - 1.9600000000000002
#   - 1.9800000000000002
#   - 2.0
#   - 2.0200000000000005
#   - 2.04
#   - 2.0600000000000005
#   - 2.08
#   - 2.1000000000000005
#   - 2.12
#   - 2.1400000000000006
#   - 2.16
# - - 1.7
#   - 1.72
#   - 1.74
#   - 1.76
#   - 1.78
#   - 1.8
#   - 1.82
#   - 1.84
#   - 1.86
#   - 1.8800000000000001
#   - 1.9000000000000001
#   - 1.9200000000000002
#   - 1.9400000000000002
#   - 1.9600000000000002
#   - 1.9800000000000002
#   - 2.0
#   - 2.0200000000000005
#   - 2.04
#   - 2.0600000000000005
#   - 2.08
#   - 2.1000000000000005
#   - 2.12
#   - 2.1400000000000006
#   - 2.16
# minimisation:
#   combined: true
#   correlated: false
