BkgFunc:
- kPol2
BkgFuncVn:
- kLin
BoundMean: 0
Bspecie: Ball
Dmeson: Dplus
DrawVnComps: false
FixMean:
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
FixSigma:
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
FixSigmaRatio: 0
FixSigmaToFirstPeak: 0
InclRefl: false
InclSecPeak:
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
IncludeTempls: false
MassMax:
- 2.029999999999998
MassMin:
- 1.73
MeanFile: ''
NSigma4SB:
- 4
- 4
- 4
- 4
- 4
- 4
- 4
- 4
- 4
- 4
- 4
- 3
- 3
- 1
Rebin:
- 1
ReflFile: ''
ReflFunc: ''
SgnFunc:
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
Sigma:
- 0.012
SigmaFile: ''
SigmaFileSecPeak: ''
SigmaMultFactor: 1.0
SigmaMultFactorSecPeak: 1.0
SigmaRatioFile: ''
SigmaSecPeak:
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
UseLikelihood: 1
anresdir: ''
axestokeep:
- Mass
- sp
- score_FD
- score_bkg
- Pt
centrality: k3040
combined: true
correlatedPath: /home/mdicosta/FlowDplus/FinalResults/3040final/cutvar_correlated
cut_variation:
  corr_bdt_cut:
    bkg_max:
    - 0.004
    sig:
      max:
      - 1.0
      min:
      - 0.06
      step:
      - 0.025
  uncorr_bdt_cut:
    bkg_max:
    - - 0.04
      - 0.02
      - 0.02
      - 0.002
    sig:
    - max:
      - 0.5
      - 0.7
      - 0.9
      - 1.0
      min:
      - 0.0
      - 0.5
      - 0.7
      - 0.9
detA: FT0c
detB: FV0a
detC: TPCtot
eff_filename: /home/mdicosta/Datasets/eff/AnalysisResults_3050_334909.root
enableRef: false
flow_files:
- /home/mdicosta/Datasets/3050/MERGED_0.root
- /home/mdicosta/Datasets/3050/MERGED_1.root
- /home/mdicosta/Datasets/3050/MERGED_2.root
- /home/mdicosta/Datasets/3050/MERGED_3.root
- /home/mdicosta/Datasets/3050/MERGED_4.root
- /home/mdicosta/Datasets/3050/MERGED_5.root
- /home/mdicosta/Datasets/3050/MERGED_6.root
- /home/mdicosta/Datasets/3050/MERGED_7.root
- /home/mdicosta/Datasets/3050/MERGED_8.root
- /home/mdicosta/Datasets/3050/MERGED_9.root
- /home/mdicosta/Datasets/3050/MERGED_10.root
harmonic: 2
inv_mass_bins:
- - 1.73
  - 1.7449999999999999
  - 1.7599999999999998
  - 1.7749999999999997
  - 1.7899999999999996
  - 1.8049999999999995
  - 1.8199999999999994
  - 1.8349999999999993
  - 1.8499999999999992
  - 1.864999999999999
  - 1.879999999999999
  - 1.894999999999999
  - 1.9099999999999988
  - 1.9249999999999987
  - 1.9399999999999986
  - 1.9549999999999985
  - 1.9699999999999984
  - 1.9849999999999983
  - 1.9999999999999982
  - 2.014999999999998
  - 2.029999999999998
minimisation:
  combined: true
  correlated: false
nworkers: 1
out_dir: /home/mdicosta/FlowDplus/FinalResults/3040final/fitsyst/latest/trails/pt_15_20
ptmaxs:
- 2.0
ptmins:
- 1.5
rebin: 1
res_file: /home/mdicosta/Datasets/Reso/resosp3040l_PASS4_full_PbPb_Reso.root
shapes:
  B:
    fonll: /home/mdicosta/FlowDplus/MLanalysis/PtWeights/fonll_pythia_beautyFFee_charmhadrons_5dot5tev_y0dot5.root
    tamu:
      enabled: true
      file:
        B: /home/mdicosta/alice/DmesonAnalysis/models/tamu/B_TAMU_RAA_5TeV_3050.txt
        Bs: ''
  D:
    fonll: /home/mdicosta/FlowDplus/MLanalysis/PtWeights/fonll_pythia_beautyFFee_charmhadrons_5dot5tev_y0dot5.root
    tamu:
      enabled: true
      file: /home/mdicosta/alice/DmesonAnalysis/models/tamu/PromptD0_TAMU_RAA_5TeV_3050.txt
skimDir: /home/mdicosta/Datasets/3050/skim3040keepbkg/pre/AnRes/
skim_out_dir: /home/mdicosta/FlowDplus/FinalResults/3040final/fitsyst/latest
smooth: 100
suffix: config_3040_combined_FixSigma-2_BkgFuncVn-0_BkgFunc-1_Rebin-0_inv_mass_bins-6_MassMin-6_MassMax-6
use_inv_mass_bins: false
vn_method: sp
