cutvars:
  Pt:
    max:
    - 2.5
    - 3.0
    min:
    - 2.0
    - 2.5
    name: pt_cand
  score_FD:
    max:
    - 1.0
    - 1.0
    min:
    - 0.49
    - 0.49
    name: score_FD
  score_bkg:
    max:
    - 0.11
    - 0.11
    min:
    - 0.0
    - 0.0
    name: score_bkg
icutset: 13
