cutvars:
  Pt:
    max:
    - 2.0
    min:
    - 1.5
    name: pt_cand
  score_FD:
    max:
    - 1.0
    min:
    - 0.9
    name: score_FD
  score_bkg:
    max:
    - 0.002
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.95
fitrangemin:
- 1.75
icutset: 3
