cutvars:
  Pt:
    max:
    - 1.5
    - 2.0
    - 2.5
    - 3.0
    - 3.5
    - 4.0
    - 5.0
    - 6.0
    - 7.0
    - 8.0
    - 10.0
    - 12.0
    - 16.0
    - 24.0
    min:
    - 1.0
    - 1.5
    - 2.0
    - 2.5
    - 3.0
    - 3.5
    - 4.0
    - 5.0
    - 6.0
    - 7.0
    - 8.0
    - 10.0
    - 12.0
    - 16.0
    name: pt_cand
  score_FD:
    max:
    - 0.4
    - 0.4
    - 0.2
    - 0.3
    - 0.3
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.3
    - 0.4
    - 0.3
    - 0.5
    min:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    name: score_FD
  score_bkg:
    max:
    - 0.01
    - 0.04
    - 0.03
    - 0.06
    - 0.06
    - 0.1
    - 0.03
    - 0.1
    - 0.04
    - 0.024
    - 0.006
    - 0.006
    - 0.18
    - 0.06
    min:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    name: score_bkg
icutset: 0
