cutvars:
  Pt:
    max:
    - 3.5
    min:
    - 3.0
    name: pt_cand
  score_FD:
    max:
    - 0.85
    min:
    - 0.7
    name: score_FD
  score_bkg:
    max:
    - 0.01
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.92
fitrangemin:
- 1.75
icutset: 3
