# using sample with a given bdt cut set below
ptbins:
-   range: [1.0, 1.5]
    MaxChi2: 10
    MinSignificance: 5
    MaxSignificance: 500
    BkgFuncVn: ["kLin", "kPol2"]
    BkgFunc: ["kLin", "kPol2", "kPol3"]
    Rebin: [1,2,3]
    inv_mass_bins_steps: [0.01, 0.02]
    FixMean: [1, 0]
    MassMin: [1.71, 1.79]
    MassMax: [1.92, 1.98]
-   range: [1.5, 2.0]
    MaxChi2: 10
    MinSignificance: 5
    MaxSignificance: 500
    BkgFuncVn: ["kLin", "kPol2"]
    BkgFunc: ["kLin", "kPol2", "kPol3"]
    Rebin: [1,2,3]
    inv_mass_bins_steps: [0.01, 0.02]
    FixMean: [1, 0]
    MassMin: [1.71, 1.79]
    MassMax: [1.92, 1.98]
-   range: [2.0, 2.5]
    MaxChi2: 15
    MinSignificance: 5
    MaxSignificance: 500
    BkgFuncVn: ["kLin", "kPol2"]
    BkgFunc: ["kLin", "kPol2", "kPol3"]
    Rebin: [1,2,3]
    inv_mass_bins_steps: [0.01, 0.02]
    FixMean: [1, 0]
    MassMin: [1.71, 1.79]
    MassMax: [1.92, 1.98]
-   range: [2.5, 3.0]
    MaxChi2: 15
    MinSignificance: 5
    MaxSignificance: 500
    BkgFuncVn: ["kLin", "kPol2"]
    BkgFunc: ["kLin", "kPol2", "kPol3"]
    Rebin: [1,2,3]
    inv_mass_bins_steps: [0.01, 0.02]
    FixMean: [1, 0]
    MassMin: [1.71, 1.79]
    MassMax: [1.92, 1.98]
-   range: [3.0, 3.5]
    MaxChi2: 20
    MinSignificance: 5
    MaxSignificance: 500
    BkgFuncVn: ["kLin", "kPol2"]
    BkgFunc: ["kLin", "kPol2", "kPol3"]
    Rebin: [1,2,3]
    inv_mass_bins_steps: [0.01, 0.02]
    FixMean: [1, 0]
    MassMin: [1.71, 1.79]
    MassMax: [1.92, 1.98]
-   range: [3.5, 4.0]
    MaxChi2: 20
    MinSignificance: 5
    MaxSignificance: 500
    BkgFuncVn: ["kLin", "kPol2"]
    BkgFunc: ["kLin", "kPol2", "kPol3"]
    Rebin: [1,2,3]
    inv_mass_bins_steps: [0.01, 0.02]
    FixMean: [1, 0]
    MassMin: [1.71, 1.79]
    MassMax: [1.92, 1.98]
-   range: [4.0, 5.0]
    MaxChi2: 20
    MinSignificance: 5
    MaxSignificance: 500
    BkgFuncVn: ["kLin", "kPol2"]
    BkgFunc: ["kLin", "kPol2", "kPol3"]
    Rebin: [1,2,3]
    inv_mass_bins_steps: [0.01, 0.02]
    FixMean: [1, 0]
    MassMin: [1.71, 1.79]
    MassMax: [1.92, 1.98]
-   range: [5.0, 6.0]
    MaxChi2: 20
    MinSignificance: 5
    MaxSignificance: 500
    BkgFuncVn: ["kLin", "kPol2"]
    BkgFunc: ["kLin", "kPol2", "kPol3"]
    Rebin: [1,2,3]
    inv_mass_bins_steps: [0.01, 0.02]
    FixMean: [1, 0]
    MassMin: [1.71, 1.79]
    MassMax: [1.92, 1.98]
-   range: [6.0, 7.0]
    MaxChi2: 20
    MinSignificance: 5
    MaxSignificance: 500
    BkgFuncVn: ["kLin", "kPol2"]
    BkgFunc: ["kLin", "kPol2", "kPol3"]
    Rebin: [1,2,3]
    inv_mass_bins_steps: [0.01, 0.02]
    FixMean: [1, 0]
    MassMin: [1.71, 1.79]
    MassMax: [1.92, 1.98]
-   range: [7.0, 8.0]
    MaxChi2: 20
    MinSignificance: 5
    MaxSignificance: 500
    BkgFuncVn: ["kLin", "kPol2"]
    BkgFunc: ["kLin", "kPol2", "kPol3"]
    Rebin: [1,2,3]
    inv_mass_bins_steps: [0.01, 0.02]
    FixMean: [1, 0]
    MassMin: [1.71, 1.79]
    MassMax: [1.92, 1.98]
-   range: [8.0, 10.0]
    MaxChi2: 20
    MinSignificance: 5
    MaxSignificance: 500
    BkgFuncVn: ["kLin", "kPol2"]
    BkgFunc: ["kLin", "kPol2", "kPol3"]
    Rebin: [1,2,3]
    inv_mass_bins_steps: [0.01, 0.02]
    FixMean: [1, 0]
    MassMin: [1.71, 1.79]
    MassMax: [1.92, 1.98]
-   range: [10.0, 12.0]
    MaxChi2: 20
    MinSignificance: 5
    MaxSignificance: 500
    BkgFuncVn: ["kLin", "kPol2"]
    BkgFunc: ["kLin", "kPol2", "kPol3"]
    Rebin: [1,2,3]
    inv_mass_bins_steps: [0.01, 0.02]
    FixMean: [1, 0]
    MassMin: [1.69, 1.72]
    MassMax: [1.98, 2.01]
-   range: [12.0, 16.0]
    MaxChi2: 20
    MinSignificance: 5
    MaxSignificance: 500
    BkgFuncVn: ["kLin", "kPol2"]
    BkgFunc: ["kLin", "kPol2", "kPol3"]
    Rebin: [1,2,3]
    inv_mass_bins_steps: [0.01, 0.02]
    FixMean: [1, 0]
    MassMin: [1.70, 1.75]
    MassMax: [2.13, 2.08]
-   range: [16.0, 24.0]
    MaxChi2: 20
    MinSignificance: 5
    MaxSignificance: 500
    BkgFuncVn: ["kLin", "kPol2"]
    BkgFunc: ["kLin", "kPol2", "kPol3"]
    Rebin: [1,2,3]
    inv_mass_bins_steps: [0.01, 0.02]
    FixMean: [1, 0]
    MassMin: [1.70, 1.75]
    MassMax: [2.13, 2.08]