RebinSparse:
  Mass: -1
  Pt: -1
  cent: -1
  score_FD: -1
  score_bkg: -1
  sp: -1
axestokeep:
- Mass
- sp
bdt_cut:
  bkg_cuts:
  - 0.02
  - 0.04
  - 0.03
  - 0.06
  - 0.06
  - 0.1
  - 0.03
  - 0.1
  - 0.02
  - 0.024
  - 0.006
  - 0.006
  - 0.15
  - 0.09
  sig_maxs:
  - - 0.4
    - 0.7
    - 0.9
    - 1.0
  - - 0.5
    - 0.7
    - 0.9
    - 1.0
  - - 0.2
    - 0.45
    - 0.75
    - 0.9
    - 1.0
  - - 0.3
    - 0.5
    - 0.75
    - 0.9
    - 1.0
  - - 0.3
    - 0.5
    - 0.7
    - 0.85
    - 1.0
  - - 0.25
    - 0.4
    - 0.7
    - 0.9
    - 1.0
  - - 0.25
    - 0.45
    - 0.65
    - 0.85
    - 1.0
  - - 0.25
    - 0.45
    - 0.65
    - 0.85
    - 1.0
  - - 0.25
    - 0.45
    - 0.65
    - 0.85
    - 1.0
  - - 0.25
    - 0.45
    - 0.65
    - 0.85
    - 1.0
  - - 0.3
    - 0.5
    - 0.75
    - 1.0
  - - 0.4
    - 0.6
    - 0.75
    - 1.0
  - - 0.4
    - 0.6
    - 0.75
    - 1.0
  - - 0.5
    - 0.7
    - 1.0
  sig_mins:
  - - 0.0
    - 0.4
    - 0.7
    - 0.9
  - - 0.0
    - 0.5
    - 0.7
    - 0.9
  - - 0.0
    - 0.2
    - 0.45
    - 0.75
    - 0.9
  - - 0.0
    - 0.3
    - 0.5
    - 0.75
    - 0.9
  - - 0.0
    - 0.3
    - 0.5
    - 0.7
    - 0.85
  - - 0.0
    - 0.25
    - 0.4
    - 0.7
    - 0.9
  - - 0.0
    - 0.25
    - 0.45
    - 0.65
    - 0.85
  - - 0.0
    - 0.25
    - 0.45
    - 0.65
    - 0.85
  - - 0.0
    - 0.25
    - 0.45
    - 0.65
    - 0.85
  - - 0.0
    - 0.25
    - 0.45
    - 0.65
    - 0.85
  - - 0.0
    - 0.3
    - 0.5
    - 0.75
  - - 0.0
    - 0.4
    - 0.6
    - 0.75
  - - 0.0
    - 0.4
    - 0.6
    - 0.75
  - - 0.0
    - 0.5
    - 0.7
centrality: k3040
flow_files:
- /home/mdicosta/Datasets/3050/MERGED_0.root
- /home/mdicosta/Datasets/3050/MERGED_1.root
- /home/mdicosta/Datasets/3050/MERGED_2.root
- /home/mdicosta/Datasets/3050/MERGED_3.root
- /home/mdicosta/Datasets/3050/MERGED_4.root
- /home/mdicosta/Datasets/3050/MERGED_5.root
- /home/mdicosta/Datasets/3050/MERGED_6.root
- /home/mdicosta/Datasets/3050/MERGED_7.root
- /home/mdicosta/Datasets/3050/MERGED_8.root
- /home/mdicosta/Datasets/3050/MERGED_9.root
- /home/mdicosta/Datasets/3050/MERGED_10.root
ptmaxs:
- 1.5
- 2.0
- 2.5
- 3.0
- 3.5
- 4.0
- 5.0
- 6.0
- 7.0
- 8.0
- 10.0
- 12.0
- 16.0
- 24.0
ptmins:
- 1.0
- 1.5
- 2.0
- 2.5
- 3.0
- 3.5
- 4.0
- 5.0
- 6.0
- 7.0
- 8.0
- 10.0
- 12.0
- 16.0
skim_out_dir: /home/mdicosta/FlowDplus/FinalResults/3040final/fitsyst/latest
