cutvars:
  Pt:
    max:
    - 4.0
    min:
    - 3.5
    name: pt_cand
  score_FD:
    max:
    - 0.7
    min:
    - 0.4
    name: score_FD
  score_bkg:
    max:
    - 0.03
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.98
fitrangemin:
- 1.75
icutset: 2
