cutvars:
  Pt:
    max:
    - 10.0
    min:
    - 8.0
    name: pt_cand
  score_FD:
    max:
    - 0.3
    min:
    - 0.0
    name: score_FD
  score_bkg:
    max:
    - 0.006
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.98
fitrangemin:
- 1.66
icutset: 0
