cutvars:
  Pt:
    max:
    - 1.5
    min:
    - 1.0
    name: pt_cand
  score_FD:
    max:
    - 0.75
    min:
    - 0.4
    name: score_FD
  score_bkg:
    max:
    - 0.02
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.92
fitrangemin:
- 1.71
icutset: 1
