BkgFunc:
- kPol2
BkgFuncVn:
- kLin
BoundMean: 0
Bspecie: Ball
Dmeson: Dplus
DrawVnComps: false
FixMean:
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
FixSigma:
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
FixSigmaRatio: 0
FixSigmaToFirstPeak: 0
InclRefl: false
InclSecPeak:
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
- 0
IncludeTempls: false
MassMax:
- 2.164999999999997
MassMin:
- 1.7
MeanFile: ''
NSigma4SB:
- 4
- 4
- 4
- 4
- 4
- 4
- 4
- 4
- 4
- 4
- 4
- 3
- 3
- 1
Rebin:
- 1
ReflFile: ''
ReflFunc: ''
SgnFunc:
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
- kGaus
Sigma:
- 0.02
SigmaFile: ''
SigmaFileSecPeak: ''
SigmaMultFactor: 1.0
SigmaMultFactorSecPeak: 1.0
SigmaRatioFile: ''
SigmaSecPeak:
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
- 0.008
UseLikelihood: 1
anresdir: ''
axestokeep:
- Mass
- sp
- score_FD
- score_bkg
- Pt
centrality: k3040
combined: true
correlatedPath: /home/mdicosta/FlowDplus/FinalResults/3040final/cutvar_correlated
cut_variation:
  corr_bdt_cut:
    bkg_max:
    - 0.006
    sig:
      max:
      - 1.0
      min:
      - 0.06
      step:
      - 0.025
  uncorr_bdt_cut:
    bkg_max:
    - - 0.006
      - 0.006
      - 0.002
      - 0.002
    sig:
    - max:
      - 0.4
      - 0.6
      - 0.75
      - 1.0
      min:
      - 0.0
      - 0.4
      - 0.6
      - 0.75
detA: FT0c
detB: FV0a
detC: TPCtot
eff_filename: /home/mdicosta/Datasets/eff/AnalysisResults_3050_334909.root
enableRef: false
flow_files:
- /home/mdicosta/Datasets/3050/MERGED_0.root
- /home/mdicosta/Datasets/3050/MERGED_1.root
- /home/mdicosta/Datasets/3050/MERGED_2.root
- /home/mdicosta/Datasets/3050/MERGED_3.root
- /home/mdicosta/Datasets/3050/MERGED_4.root
- /home/mdicosta/Datasets/3050/MERGED_5.root
- /home/mdicosta/Datasets/3050/MERGED_6.root
- /home/mdicosta/Datasets/3050/MERGED_7.root
- /home/mdicosta/Datasets/3050/MERGED_8.root
- /home/mdicosta/Datasets/3050/MERGED_9.root
- /home/mdicosta/Datasets/3050/MERGED_10.root
harmonic: 2
inv_mass_bins:
- - 1.7
  - 1.7149999999999999
  - 1.7299999999999998
  - 1.7449999999999997
  - 1.7599999999999996
  - 1.7749999999999995
  - 1.7899999999999994
  - 1.8049999999999993
  - 1.8199999999999992
  - 1.834999999999999
  - 1.849999999999999
  - 1.8649999999999989
  - 1.8799999999999988
  - 1.8949999999999987
  - 1.9099999999999986
  - 1.9249999999999985
  - 1.9399999999999984
  - 1.9549999999999983
  - 1.9699999999999982
  - 1.984999999999998
  - 1.999999999999998
  - 2.014999999999998
  - 2.0299999999999976
  - 2.0449999999999977
  - 2.059999999999998
  - 2.0749999999999975
  - 2.089999999999997
  - 2.1049999999999973
  - 2.1199999999999974
  - 2.134999999999997
  - 2.149999999999997
  - 2.164999999999997
minimisation:
  combined: true
  correlated: false
nworkers: 1
out_dir: /home/mdicosta/FlowDplus/FinalResults/3040final/fitsyst/latest/trails/pt_100_120
ptmaxs:
- 12.0
ptmins:
- 10.0
rebin: 1
res_file: /home/mdicosta/Datasets/Reso/resosp3040l_PASS4_full_PbPb_Reso.root
shapes:
  B:
    fonll: /home/mdicosta/FlowDplus/MLanalysis/PtWeights/fonll_pythia_beautyFFee_charmhadrons_5dot5tev_y0dot5.root
    tamu:
      enabled: true
      file:
        B: /home/mdicosta/alice/DmesonAnalysis/models/tamu/B_TAMU_RAA_5TeV_3050.txt
        Bs: ''
  D:
    fonll: /home/mdicosta/FlowDplus/MLanalysis/PtWeights/fonll_pythia_beautyFFee_charmhadrons_5dot5tev_y0dot5.root
    tamu:
      enabled: true
      file: /home/mdicosta/alice/DmesonAnalysis/models/tamu/PromptD0_TAMU_RAA_5TeV_3050.txt
skimDir: /home/mdicosta/Datasets/3050/skim3040keepbkg/pre/AnRes/
skim_out_dir: /home/mdicosta/FlowDplus/FinalResults/3040final/fitsyst/latest
smooth: 100
suffix: config_3040_combined_FixSigma-2_BkgFuncVn-0_BkgFunc-1_Rebin-0_inv_mass_bins-7_MassMin-7_MassMax-7
use_inv_mass_bins: false
vn_method: sp
