cutvars:
  Pt:
    max:
    - 4.0
    min:
    - 3.5
    name: pt_cand
  score_FD:
    max:
    - 0.4
    min:
    - 0.25
    name: score_FD
  score_bkg:
    max:
    - 0.07
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.98
fitrangemin:
- 1.79
icutset: 1
