cutvars:
  Pt:
    max:
    - 7.0
    min:
    - 6.0
    name: pt_cand
  score_FD:
    max:
    - 0.65
    min:
    - 0.45
    name: score_FD
  score_bkg:
    max:
    - 0.02
    min:
    - 0.0
    name: score_bkg
fitrangemax:
- 1.95
fitrangemin:
- 1.7
icutset: 2
