cutvars:
  InvMass:
    axisnum: 3
    name: inv_mass
  ML_output_Bkg:
    axisnum: 0
    max:
    - 0.2
    - 0.2
    min:
    - 0.0
    - 0.0
    name: ML_output_Bkg
  ML_output_FD:
    axisnum: 1
    max:
    - 1.0
    - 1.0
    min:
    - 0.05
    - 0.05
    name: ML_output_FD
  Pt:
    axisnum: 4
    max:
    - 3.0
    - 4.0
    min:
    - 2.0
    - 3.0
    name: pt_cand
icutset: 0
